/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mylibrary;

import net.accelbyte.sdk.core.AccelByteSDK;
import net.accelbyte.sdk.core.client.OkhttpClient;
import net.accelbyte.sdk.core.repository.DefaultConfigRepository;
import net.accelbyte.sdk.core.repository.DefaultTokenRepository;

public class Library {
    public boolean someLibraryMethod() {
        // Create default HTTP client, token repository, and config repository instance

        OkhttpClient httpClient = new OkhttpClient();
        DefaultTokenRepository tokenRepository = new DefaultTokenRepository();
        DefaultConfigRepository configRepository = new DefaultConfigRepository();

        // Create SDK instance

        AccelByteSDK sdk = new AccelByteSDK(
                httpClient,
                tokenRepository,
                configRepository);

        sdk.loginClient();

        return true;
    }
}
